'use client';

import React, { useEffect } from 'react';
import { TrendingUp, TrendingDown, ShieldAlert, Award, ArrowUpRight, Download, MessageSquare, CheckCircle2, AlertCircle, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';
import confetti from 'canvas-confetti';
import { ResearchReport } from '../lib/types';

interface VerdictBannerProps {
  report: ResearchReport;
  onOpenChat: () => void;
}

export function VerdictBanner({ report, onOpenChat }: VerdictBannerProps) {
  const isInvest = report.decision === 'INVEST';
  const isPass = report.decision === 'PASS';
  const isWatch = report.decision === 'WATCH';

  useEffect(() => {
    if (isInvest) {
      // Celebrate high conviction BUY with confetti!
      const duration = 2.5 * 1000;
      const animationEnd = Date.now() + duration;
      const defaults = { startVelocity: 30, spread: 360, ticks: 60, zIndex: 0 };

      const interval: NodeJS.Timeout = setInterval(function () {
        const timeLeft = animationEnd - Date.now();
        if (timeLeft <= 0) {
          return clearInterval(interval);
        }
        const particleCount = 50 * (timeLeft / duration);
        confetti({
          ...defaults,
          particleCount,
          origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 },
          colors: ['#10b981', '#6366f1', '#a5b4fc'],
        });
        confetti({
          ...defaults,
          particleCount,
          origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 },
          colors: ['#10b981', '#6366f1', '#a5b4fc'],
        });
      }, 250);

      return () => clearInterval(interval);
    }
  }, [isInvest]);

  function randomInRange(min: number, max: number) {
    return Math.random() * (max - min) + min;
  }

  const upside =
    ((report.metrics.targetPrice - report.metrics.currentPrice) / report.metrics.currentPrice) * 100;

  const exportMemo = () => {
    const markdown = `# ApexIQ Institutional Investment Memo: ${report.companyName} (${report.ticker})
**Date**: ${new Date().toLocaleDateString()}
**Sector**: ${report.sector}
**Horizon**: ${report.horizon}
**Decision**: ${report.decision} (Alpha Conviction: ${report.convictionScore}%)
**Current Price**: ${report.metrics.currency}${report.metrics.currentPrice} | **Target Price**: ${report.metrics.currency}${report.metrics.targetPrice} (${upside >= 0 ? '+' : ''}${upside.toFixed(1)}%)

---

## 1. Executive Summary
${report.summary}

## 2. Core Investment Thesis
${report.thesis.map((t, idx) => `${idx + 1}. ${t}`).join('\n')}

## 3. Key Catalysts
${report.keyCatalysts.map((c, idx) => `- ${c}`).join('\n')}

## 4. Key Risks & Headwinds
${report.keyRisks.map((r, idx) => `- ${r}`).join('\n')}

---
*Generated by ApexIQ Multi-Agent LangGraph AI Platform*
`;

    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ApexIQ_Memo_${report.ticker}_${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
      className={`relative overflow-hidden rounded-3xl p-6 sm:p-8 border transition-all ${
        isInvest
          ? 'glass-panel border-emerald-500/50 glow-emerald bg-gradient-to-br from-[#090A0F] via-[#0E1714] to-[#090A0F]'
          : isPass
          ? 'glass-panel border-rose-500/50 glow-rose bg-gradient-to-br from-[#090A0F] via-[#170E10] to-[#090A0F]'
          : 'glass-panel border-amber-500/50 glow-amber bg-gradient-to-br from-[#090A0F] via-[#17140E] to-[#090A0F]'
      }`}
    >
      {/* Background Icon Watermark */}
      <div className="absolute -right-6 -bottom-6 opacity-5 pointer-events-none">
        {isInvest ? (
          <TrendingUp className="w-64 h-64 text-emerald-400" />
        ) : isPass ? (
          <TrendingDown className="w-64 h-64 text-rose-400" />
        ) : (
          <ShieldAlert className="w-64 h-64 text-amber-400" />
        )}
      </div>

      <div className="relative z-10 flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
        {/* Left: Company & Verdict */}
        <div className="space-y-4 max-w-2xl">
          <div className="flex flex-wrap items-center gap-2">
            <span className="px-3 py-1 rounded-full bg-white/10 text-xs font-bold text-white border border-white/10 uppercase tracking-wider">
              {report.sector}
            </span>
            <span className="px-3 py-1 rounded-full bg-indigo-500/20 text-xs font-bold text-indigo-300 border border-indigo-500/30">
              Horizon: {report.horizon}
            </span>
            {report.isLiveLLM && (
              <span className="px-2.5 py-0.5 rounded-full bg-purple-500/20 text-[11px] font-bold text-purple-300 border border-purple-500/30 flex items-center space-x-1">
                <Sparkles className="w-3 h-3 text-purple-300 mr-1" />
                Live AI Generated
              </span>
            )}
          </div>

          <div>
            <h1 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
              {report.companyName} <span className="text-slate-400 font-mono text-2xl sm:text-4xl">({report.ticker})</span>
            </h1>
            <p className="mt-2 text-sm sm:text-base text-slate-300 leading-relaxed font-normal">
              {report.summary}
            </p>
          </div>

          {/* Core Thesis Bullets */}
          <div className="pt-2 space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">Institutional Thesis Drivers:</h4>
            <div className="grid grid-cols-1 gap-2">
              {report.thesis.map((point, idx) => (
                <div key={idx} className="flex items-start space-x-2.5 text-xs sm:text-sm text-slate-200 bg-white/[0.03] p-2.5 rounded-xl border border-white/5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span>{point}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right: Decision Badge & Valuation Box */}
        <div className="w-full lg:w-auto flex flex-col sm:flex-row lg:flex-col items-stretch sm:items-center lg:items-end gap-4 shrink-0">
          {/* Main Verdict Badge */}
          <div
            className={`flex flex-col items-center justify-center p-6 rounded-2xl border text-center shadow-2xl w-full sm:w-64 ${
              isInvest
                ? 'bg-emerald-500/20 border-emerald-500/60 text-emerald-300 shadow-emerald-500/20'
                : isPass
                ? 'bg-rose-500/20 border-rose-500/60 text-rose-300 shadow-rose-500/20'
                : 'bg-amber-500/20 border-amber-500/60 text-amber-300 shadow-amber-500/20'
            }`}
          >
            <span className="text-[11px] font-black uppercase tracking-widest text-slate-300 mb-1">Committee Verdict</span>
            <div className="flex items-center space-x-2">
              {isInvest && <TrendingUp className="w-8 h-8 text-emerald-400" />}
              {isPass && <TrendingDown className="w-8 h-8 text-rose-400" />}
              {isWatch && <ShieldAlert className="w-8 h-8 text-amber-400" />}
              <span className="text-3xl sm:text-4xl font-black tracking-tight">{report.decision}</span>
            </div>
            <div className="mt-2 flex items-center space-x-1.5 text-xs font-bold bg-black/40 px-3 py-1 rounded-full border border-white/10">
              <Award className="w-3.5 h-3.5 text-indigo-400" />
              <span>Conviction Score: {report.convictionScore}%</span>
            </div>
          </div>

          {/* Upside & Valuation Box */}
          <div className="glass-card p-4 rounded-2xl border border-white/10 w-full sm:w-64 text-center space-y-2">
            <div className="flex items-center justify-between text-xs text-slate-400 border-b border-white/10 pb-2">
              <span>Current Price:</span>
              <span className="font-bold text-white font-mono">{report.metrics.currency}{report.metrics.currentPrice}</span>
            </div>
            <div className="flex items-center justify-between text-xs text-slate-400">
              <span>Implied Target:</span>
              <span className="font-bold text-indigo-400 font-mono text-sm">{report.metrics.currency}{report.metrics.targetPrice}</span>
            </div>
            <div className="pt-2 flex items-center justify-center space-x-1 font-bold text-sm">
              <span>Expected Upside:</span>
              <span className={`font-mono flex items-center ${upside >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                {upside >= 0 ? '+' : ''}{upside.toFixed(1)}%
                <ArrowUpRight className="w-4 h-4 ml-0.5" />
              </span>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center justify-end space-x-2 w-full sm:w-64 pt-1">
            <button
              onClick={onOpenChat}
              className="flex-1 flex items-center justify-center space-x-1.5 py-2.5 px-3 rounded-xl bg-indigo-500/20 hover:bg-indigo-500/30 border border-indigo-500/40 text-indigo-300 font-bold text-xs transition-all"
            >
              <MessageSquare className="w-4 h-4" />
              <span>Grill AI</span>
            </button>
            <button
              onClick={exportMemo}
              className="flex-1 flex items-center justify-center space-x-1.5 py-2.5 px-3 rounded-xl bg-white/10 hover:bg-white/15 border border-white/10 text-white font-bold text-xs transition-all shadow-sm"
            >
              <Download className="w-4 h-4" />
              <span>Memo MD</span>
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
